import re
import os
import json
from data_sft import INPUT_TEMPLATE
from huggingface_hub import upload_file,create_repo


"""
{
    "conversations": [
        {
            "from": "human",
            "value": "\n<video>\n\nYou are an expert for evaluating and thinking about the quality of AI videos from diverse dimensions.\n\nWe would like to evaluate its quality from three dimensions: 'visual quality', 'text-to-video alignment' and 'physical consistency'. Below is the definition of each dimension: \n(1) \nThe dimension 'visual quality' cares about the video's visual and optical propertities, including 'resolution, overall clarity, local blurriness, smoothness, stability of brightness/contrast, distortion/misalignment, abrupt changes, and any other factors the affect the watching experience'. The keywords written by the annotators are also mostly derived from the above factors.\n\n(2) \nThe dimension 't2v_alignment' mainly assesses whether the generated video fully and accurately depicts the elements mentioned in the text prompt, such as characters, actions, animals, etc., as well as background, quantity, color, weather, and so on. So the keywords written by annotators sometimes only indicate the elements that are missing from the video.\n\n(3) \nThe dimension 'physical/common-sense consistency' mainly examines whether there are any violations of common sense, physical laws, or any other aspects in the video that appear strange or unnatural. Most of the keywords provided by annotators point out the specific abnormalities or inconsistencies they observed in the video.\n\n\nHere we provide an AI video generated by text-to-video models and its text prompt: \nA playful kitten pounces on a dangling string, swats it with its paws, then leaps and chases it across the room.\n\nBased on the video content and the dimension definitions, please think about and evaluate the video quality and give the quality score. \nThe quality score must be in 1.0 - 5.0, and the thinking process should be of appropriate length and expression.\n\n"
        },
        {
            "from": "gpt",
            "value": "\n<think>\nLooking at the video frames provided, I need to analyze this AI-generated video across three dimensions: visual quality, text-to-video alignment, and physical consistency.\n\nFirst, let me understand what the text prompt is asking for:\n\"A playful kitten pounces on a dangling string, swats it with its paws, then leaps and chases it across the room\"\n\nKey elements expected:\n1. A playful kitten\n2. A dangling string\n3. The kitten should pounce on the string\n4. The kitten should swat the string with its paws\n5. The kitten should leap and chase the string\n6. This should happen across a room\n\nNow let me analyze the video frames:\n\nLooking at the frames, I can see:\n- There is indeed a small kitten, appears to be a tabby and white kitten\n- There is a dangling string visible in the frames\n- The kitten appears to be interacting with the string\n- The setting appears to be a plain white background, not really a \"room\" setting\n- The kitten does seem to be moving around the string\n\n**Visual Quality Analysis:**\n\nResolution and Clarity: The frames show decent resolution, but there are some issues with clarity. The kitten appears somewhat blurry in several frames, especially during movement sequences. The background is very plain white, which makes it hard to assess detail rendering.\n\nStability and Smoothness: Looking at the sequence of frames, there appear to be some stability issues. The kitten's position seems to jump around somewhat unnaturally between frames. The movement doesn't appear completely smooth.\n\nBlurriness: There's noticeable motion blur in several frames, particularly when the kitten is moving. This affects the overall visual quality.\n\nBrightness/Contrast: The lighting appears consistent throughout, with good contrast between the kitten and the white background.\n\nDistortion: There appear to be some distortion issues with the kitten's body proportions in some frames. The kitten's limbs and body shape seem to warp or change unnaturally between frames.\n \nThe video falls short in capturing the dynamic movement described in the prompt. While the kitten and string are present, the performance lacks the energetic leaping and chasing specified. The white background fails to represent a room, and the kitten's interactions seem constrained and less playful than expected. Motion inconsistencies and visual distortions further detract from the intended cinematic experience.\n\nExamining the physical rendering reveals significant anatomical anomalies. The kitten's body undergoes unnatural transformations between frames, with limbs warping and proportions shifting unpredictably. String physics appear unrealistic, and the kitten's positioning suggests digital artifacts rather than fluid movement. These visual inconsistencies fundamentally compromise the video's believability and technical execution.\n\nThe visual quality suffers from multiple technical limitations. Blurriness and instability compound the existing structural problems, with the kitten's distorted anatomy further degrading the overall visual fidelity. Basic elements are recognizable, but the technical execution falls far short of a polished, realistic representation.\n\nAlignment between the intended text description and actual video content remains partial at best. Critical narrative elements - the room's context and the dramatic chase sequence - are notably absent. While some core interactions are captured, the video fails to fully translate the original conceptual intent.\n\nScoring reflects these critical shortcomings. Visual quality and text alignment are aligned with a score of 3, while physical consistency falls slightly to a 2 due to the extreme anatomical and physical irregularities present in the rendering.\n</think>\n\n(1) visual quality: 3\n(2) text-to-video alignment: 3\n(3) physical/common-sense consistency: 3\n"
        }
    ],
    "videos": [
        "videos/001510_u.mp4"
    ]
}
"""

"""
    "problem_id": 1,
    "problem": "Based on the figure, what role does the quartz cylinder play in the experimental setup?",
    "data_type": "image",
    "problem_type": "multiple choice",
    "options": [
        "A) It is used to focus the laser for the LDV",
        "B) It is the main weight that is being measured",
        "C) It encases the piezo-actuator to insulate it",
        "D) It serves as a medium for the laser to pass through for measurements"
    ],
    "solution": "<answer>D</answer>",
    "path": "./Knowledge/ArxivQA/images/1702.04756_0.jpg",
    "data_source": ""
"""

def main(sft_data_path,save_path):
    with open(sft_data_path,"r",encoding='utf-8') as f:
        sft_data=json.load(f)
    
    new_data=[]
    for item in sft_data:
        human_input=item['conversations'][0]['value']
        model_out=item['conversations'][1]['value']
        video_name=item['videos'][0].split('/')[-1].split('.')[0]
        t2v_prompt=human_input.split('its text prompt:')[-1].split('Based on the video content and the dimension definitions')[0].strip()
        short_res=model_out[-100:]
        pattern = r"visual quality:\s*(\d+).*?text-to-video alignment:\s*(\d+).*?physical/common-sense consistency:\s*(\d+)"
        match = re.search(pattern, short_res, re.DOTALL | re.IGNORECASE)
        if match:
            v_score = int(match.group(1))
            t_score = int(match.group(2))
            p_score = int(match.group(3))
        else:
            v_score = t_score = p_score = None
            print(f"{video_name} match failed, skipped")
            continue
        new_item={
            "problem_id": video_name,
            "problem": INPUT_TEMPLATE.substitute(t2v_prompt=t2v_prompt),
            "data_type": "video",
            "problem_type": "video eval",
            "options": [],
            "solution": f"<answer>visual quality: {v_score}; text-to-video alignment: {t_score}; physical/common-sense consistency: {p_score}</answer>",
            "path": f"./vs2_videos/{video_name}.mp4",
            "data_source": ""
        }
        new_data.append(new_item)
        
    
    
    with open(save_path, "w") as f:
        json.dump(new_data, f, indent=4)
    upload_file(
        path_or_fileobj=save_path,
        path_in_repo=save_path.split("/")[-1],
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(save_path)
    
    
    
    
if __name__ == "__main__":
    REPO_ID="hexuan21/vs2_rl_data"
    HF_TOKEN=os.environ["HF_TOKEN"]
    create_repo(
        repo_id=REPO_ID,
        token=HF_TOKEN,
        repo_type='dataset',
        private=False,
        exist_ok=True
        )
    sft_data_path="temp/sft_17k.json"
    save_path="temp/grpo_17k.json"
    main(sft_data_path,save_path)