import json
import os
from string import Template
import zipfile
import random
from tqdm import tqdm
from datasets import Dataset, Features, Value
from huggingface_hub import upload_file, create_repo

from utils_fetch_f_v import _fetch_all_frames_single,_fetch_video_single, \
                                download_video_from_data,download_video_from_parquet,download_all_frames_from_data

# LF data/dataset_info.json
"""
"dataset_name": {
  "file_name": "data.json",
  "formatting": "sharegpt",
  "columns": {
    "messages": "conversations",
    "videos": "videos"
  }
}
"""

"""
[
  {
    "conversations": [
      {
        "from": "human",
        "value": "<video>user instruction"
      },
      {
        "from": "gpt",
        "value": "model response"
      }
    ],
    "videos": [
      "video path (required)"
    ]
  }
]
"""


INPUT_TEMPLATE=Template("""You are an expert for evaluating and thinking about the quality of AI videos from diverse dimensions.

We would like to evaluate its quality from three dimensions: 'visual quality', 'text-to-video alignment' and 'physical consistency'. Below is the definition of each dimension: 
(1) visual quality: 
The dimension 'visual quality' cares about the video's visual and optical propertities, including 'resolution, overall clarity, local blurriness, smoothness, stability of brightness/contrast, distortion/misalignment, abrupt changes, and any other factors the affect the watching experience'. The keywords written by the annotators are also mostly derived from the above factors.
(2) text-to-video alignment:
The dimension 't2v_alignment' mainly assesses whether the generated video fully and accurately depicts the elements mentioned in the text prompt, such as characters, actions, animals, etc., as well as background, quantity, color, weather, and so on. So the keywords written by annotators sometimes only indicate the elements that are missing from the video.
(3) physical/common-sense consistency:
The dimension 'physical/common-sense consistency' mainly examines whether there are any violations of common sense, physical laws, or any other aspects in the video that appear strange or unnatural. Most of the keywords provided by annotators point out the specific abnormalities or inconsistencies they observed in the video.

Here we provide an AI video generated by text-to-video models and its text prompt: 
$t2v_prompt.

Based on the video content and the dimension definitions, please evaluate the video quality and give the quality score. 
The quality score must be integars in the range of 1 - 5.

""")

COT_TEMPLATE=Template("""
<think>
$thinking
</think>

(1) visual quality: $v_score
(2) text-to-video alignment: $t_score
(3) physical/common-sense consistency: $p_score
""")

NO_COT_TEMPLATE=Template("""
(1) visual quality: $v_score
(2) text-to-video alignment: $t_score
(3) physical/common-sense consistency: $p_score
""")

# another format of model output
'''
<think>
$thinking
</think>
{
    "visual quality":$v_score,
    "text-to-video alignment":$t_score,
    "physical/common-sense consistency":"$p_score
}
'''    

def zip_upload_videos(video_abs_paths, sft_data_name, batch_size):
    total = len(video_abs_paths)
    zip_files=[]
    
    if batch_size is None:
        num_batches=1
        batch_videos=video_abs_paths
        video_zip = f"{sft_data_name}_videos.zip"
        print(f"Zipping videos...")

        with zipfile.ZipFile(video_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for v_p in tqdm(batch_videos):
                f_name = os.path.basename(v_p)
                if v_p.endswith('.mp4'):
                    zipf.write(v_p, arcname=f_name)

        zip_files.append(video_zip)
        upload_file(
            path_or_fileobj=video_zip,
            path_in_repo=video_zip,
            repo_id=VIDEO_REPO_ID,
            repo_type="dataset",
            token=HF_TOKEN
        )
        os.remove(video_zip)
        
        
    else:
        num_batches = (total + batch_size - 1) // batch_size 
        print(num_batches)
        for batch_idx in range(num_batches):
            start = batch_idx * batch_size
            end = min((batch_idx + 1) * batch_size, total)
            batch_videos = video_abs_paths[start:end]

            video_zip = f"{sft_data_name}_videos_{batch_idx+1}.zip"
            print(f"Zipping videos {start}–{end} into {video_zip} ...")

            with zipfile.ZipFile(video_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for v_p in tqdm(batch_videos, desc=f"Batch {batch_idx+1}/{num_batches}"):
                    f_name = os.path.basename(v_p)
                    if v_p.endswith('.mp4'):
                        zipf.write(v_p, arcname=f_name)

            zip_files.append(video_zip)
            upload_file(
                path_or_fileobj=video_zip,
                path_in_repo=video_zip,
                repo_id=VIDEO_REPO_ID,
                repo_type="dataset",
                token=HF_TOKEN
            )
            os.remove(video_zip)



def build_sft_data(paths,sft_data_name,f_v_save_dir,visual_format,with_cot=True):
    data=[]
    for path in paths:
        data.extend(json.load(open(path,"r",encoding='utf-8')))
    
    
    
    random.seed(SEED)
    random.shuffle(data)
    test_data=data[:TEST_NUM]
    data=data[TEST_NUM:]
    
    video_abs_paths=[]
    frames_dir_abs_paths=[]
    convs=[]
    for x in tqdm(data):
        video_name=x["video_name"]
        video_url=x["video_url"]
        t2v_prompt=x["prompt"]
        v_score=x["visual_score"]
        t_score=x["t2v_score"]
        p_score=x["phy_score"]
        thinking=x["thinking"]
        human_input="<video>"+INPUT_TEMPLATE.substitute(t2v_prompt=t2v_prompt)
        if with_cot:
            model_output=COT_TEMPLATE.substitute(thinking=thinking,v_score=v_score,t_score=t_score,p_score=p_score)
        else:
            model_output=NO_COT_TEMPLATE.substitute(v_score=v_score,t_score=t_score,p_score=p_score)
        
        if visual_format in ["videos","video","v"]:
            video_path=_fetch_video_single(video_name,video_url,f_v_save_dir)
            if video_path is None:
                continue
            video_abs_paths.append(video_path)
            
            conv={
                "conversations": [
                {
                    "from": "human",
                    "value": human_input
                },
                {
                    "from": "gpt",
                    "value": model_output
                }
                ],
                "videos": [
                    f"videos/{video_name}.mp4"
                ]
            }
            
            
        if visual_format in ["frames","frame","f"]:
            frame_dir_path=_fetch_all_frames_single(video_name,video_url,f_v_save_dir)
            if frame_dir_path is None:
                continue
            frames_dir_abs_paths.append(frame_dir_path)
            human_input=human_input.replace("<video>","<image>"*len(os.listdir(frame_dir_path)))
            human_input=human_input.replace("an AI video","the video frames of an AI video")
            conv={
                "conversations": [
                {
                    "from": "human",
                    "value": human_input
                },
                {
                    "from": "gpt",
                    "value": model_output
                }
                ],
                "images": [f"frames/{video_name}/{video_name}_{i}.jpg" for i in range(len(os.listdir(frame_dir_path)))]
            }
        
        convs.append(conv)
            
    dataset = Dataset.from_list(convs)
    # dataset.push_to_hub(repo_id=REPO_ID,token=HF_TOKEN,private=False)
    
    
    train_save_path=f"{sft_data_name}.json"
    if not with_cot:
        train_save_path=f"{sft_data_name}_no_cot.json"
    if visual_format in ["frames","frame","f"]:
        train_save_path=train_save_path.replace(".json","_f.json")
    with open(train_save_path, "w") as f:
        json.dump(convs, f, indent=4)
    upload_file(
        path_or_fileobj=train_save_path,
        path_in_repo=train_save_path,
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(train_save_path)
    
    test_path=f"{sft_data_name}_test.json"
    if visual_format in ["frames","frame","f"]:
        test_path=f"{sft_data_name}_f_test.json"
        
    with open(test_path, "w") as f:
        json.dump(test_data, f, indent=4)
    upload_file(
        path_or_fileobj=test_path,
        path_in_repo=test_path,
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(test_path)
    
    if visual_format in ["videos","video","v"]:
        print("zipping videos...")
        # with zipfile.ZipFile(video_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        #     for v_p in tqdm(video_abs_paths):
        #         f_name=v_p.split('/')[-1]
        #         if v_p.endswith('.mp4'):
        #             zipf.write(v_p, arcname=f_name)  
        zip_upload_videos(video_abs_paths,sft_data_name,batch_size=None)
    
    if visual_format in ["frames","frame","f"]:
        frame_zip=f"{sft_data_name}_frames.zip"
        with zipfile.ZipFile(frame_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for frame_dir in tqdm(frames_dir_abs_paths):
                frame_dir = os.path.abspath(frame_dir)
                d_name = os.path.basename(frame_dir)
                for frame in os.listdir(frame_dir):
                    f_p = os.path.join(frame_dir, frame)
                    if os.path.isfile(f_p):
                        arcname = os.path.join(d_name, frame)
                        zipf.write(f_p, arcname=arcname)

        upload_file(
            path_or_fileobj=frame_zip,
            path_in_repo=frame_zip,
            repo_id=VIDEO_REPO_ID,
            repo_type="dataset",
            token=HF_TOKEN
        )
        os.remove(frame_zip)
        
    
            
    
    

if __name__ == "__main__":
    REPO_ID="hexuan21/vs2_sft_data"
    VIDEO_REPO_ID="hexuan21/vs2_sft_video"
    HF_TOKEN=os.environ["HF_TOKEN"]
    create_repo(
            repo_id=REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    SEED=42
    random.seed(SEED)
    
    create_repo(
            repo_id=VIDEO_REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    
    TEST_NUM=500
    sft_data_name="sft_27k"
    visual_format="v"
    with_cot=0
    data_paths=[
        f"thinking_final/{fname}" for fname in os.listdir("thinking_final") if fname.endswith('.json')
    ]
    f_v_save_dir=f"/data/xuan/data/videoscore2/f_v_all"

    # download_video_from_data(data_paths,f_v_save_dir,max_workers=12)
    
    build_sft_data(data_paths,sft_data_name,f_v_save_dir,visual_format,with_cot)
    
    
    # parquet_names=[
    #     "lab_12k_0712"
    # ]
    # sft_batch_name="lab_12k_0712"
    # repo_id="hexuan21/vs2_raw_comment"
    # f_v_save_dir=f"/data/xuan/videoscore2/f_v_all"
    # download_video_from_parquet(repo_id,parquet_names,f_v_save_dir,max_workers=8)

    
    
    
    
    # =================== Upload Large Zip
    # export GIT_LFS_SKIP_SMUDGE=1
    # git clone --depth 1 https://huggingface.co/datasets/hexuan21/vs2_sft_video
    # cd vs2_sft_video

    # git lfs install
    # hf lfs-enable-largefiles .
    # git lfs track "*.zip"
    # git lfs track "*.mp4"

    # git add .gitattributes
    # git commit -m "Enable LFS for zip/mp4 files"

    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_1.zip sft_27k_videos_1.zip
    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_2.zip sft_27k_videos_2.zip
    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_3.zip sft_27k_videos_3.zip
    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_4.zip sft_27k_videos_4.zip
    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_5.zip sft_27k_videos_5.zip
    # cp /data/xuan/workdir/VideoScore2/data/sft_27k_videos_6.zip sft_27k_videos_6.zip
    
    # git add sft_27k_videos_2.zip
    # git commit -m "update"
    
    # git push