import json
import os
from string import Template
from datasets import Dataset, Features, Value
from huggingface_hub import upload_file, create_repo
import urllib.request
import warnings
import zipfile
from tqdm import tqdm
from datasets import load_dataset
from concurrent.futures import ThreadPoolExecutor, as_completed
import random


# LF data/dataset_info.json
"""
"dataset_name": {
  "file_name": "data.json",
  "formatting": "sharegpt",
  "columns": {
    "messages": "conversations",
    "videos": "videos"
  }
}
"""

"""
[
  {
    "conversations": [
      {
        "from": "human",
        "value": "<video>user instruction"
      },
      {
        "from": "gpt",
        "value": "model response"
      }
    ],
    "videos": [
      "video path (required)"
    ]
  }
]
"""

visual_def='''
The dimension 'visual quality' cares about the video's visual and optical propertities, including 'resolution, overall clarity, local blurriness, smoothness, stability of brightness/contrast, distortion/misalignment, abrupt changes, and any other factors the affect the watching experience'. The keywords written by the annotators are also mostly derived from the above factors.
'''

t2v_def='''
The dimension 't2v_alignment' mainly assesses whether the generated video fully and accurately depicts the elements mentioned in the text prompt, such as characters, actions, animals, etc., as well as background, quantity, color, weather, and so on. So the keywords written by annotators sometimes only indicate the elements that are missing from the video.
'''

phy_def='''
The dimension 'physical/common-sense consistency' mainly examines whether there are any violations of common sense, physical laws, or any other aspects in the video that appear strange or unnatural. Most of the keywords provided by annotators point out the specific abnormalities or inconsistencies they observed in the video.
'''

SYS_PROMPT='''
You are an expert for evaluating and thinking about the quality of AI videos from diverse dimensions.
'''

INPUT_TEMPLATE=Template("""
<video>
$sys_prompt
We would like to evaluate its quality from three dimensions: 'visual quality', 'text-to-video alignment' and 'physical consistency'. Below is the definition of each dimension: 
(1) $visual_def
(2) $t2v_def
(3) $phy_def

Here we provide an AI video generated by text-to-video models and its text prompt: 
$t2v_prompt.

Based on the video content and the dimension definitions, please think about and evaluate the video quality and give the quality score. 
The quality score must be in 1.0 - 5.0, and the thinking process should be of appropriate length and expression.

""")

OUT_TEMPLATE=Template("""
<think>
$thinking
</think>

(1) visual quality: $v_score
(2) text-to-video alignment: $t_score
(3) physical/common-sense consistency: $p_score
""")

# another format of model output
'''
<think>
$thinking
</think>
{
    "visual quality":$v_score,
    "text-to-video alignment":$t_score,
    "physical/common-sense consistency":"$p_score
}
'''    


def _fetch_video_single(item, save_dir):
    name = item["video_name"]
    url = item["video_url"]
    video_path = os.path.join(save_dir, f"{name}.mp4")
    os.makedirs(os.path.dirname(video_path), exist_ok=True)
    if not os.path.exists(video_path):
        try:
            urllib.request.urlretrieve(url, video_path)
            return video_path
        except Exception as e:
            print(f"[ERROR] Download failed for {name}: {e}")
            return None
    else:
        return video_path


def download_video(paths,video_save_dir, max_workers=8):
    data = []
    for path in paths:
        with open(path, "r", encoding='utf-8') as f:
            data.extend(json.load(f))
    print(f"Total videos to download: {len(data)}")

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(_fetch_video_single, x, video_save_dir) for x in data]

        for future in tqdm(as_completed(futures), total=len(futures), desc="Downloading videos"):
            result = future.result()
            if result is None:
                continue  



def download_video_2(repo_id,parquet_names,video_save_dir,max_workers=8):
    data = load_dataset(repo_id, data_files=[f"{p_n}.parquet" for p_n in parquet_names],split="train")
    print(len(data))
    
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(_fetch_video_single, x, video_save_dir) for x in data]

        for future in tqdm(as_completed(futures), total=len(futures), desc="Downloading videos"):
            result = future.result()
            if result is None:
                continue  


def build_sft_data(paths,sft_data_name,video_save_dir):
    data=[]
    for path in paths:
        data.extend(json.load(open(path,"r",encoding='utf-8')))
    
    random.shuffle(data)
    test_data=data[:TEST_NUM]
    data=data[TEST_NUM:]
    
    video_abs_paths=[]
    convs=[]
    for x in tqdm(data):
        video_name=x["video_name"]
        video_path=_fetch_video_single(x,video_save_dir)
        if video_path is None:
            continue
        video_abs_paths.append(video_path)
    
        t2v_prompt=x["prompt"]
        v_score=x["visual_score"]
        t_score=x["t2v_score"]
        p_score=x["phy_score"]
        thinking=x["thinking"]
        
        
        conv={
            "conversations": [
            {
                "from": "human",
                "value": INPUT_TEMPLATE.substitute(sys_prompt=SYS_PROMPT,
                                                visual_def=visual_def,
                                                t2v_def=t2v_def,
                                                phy_def=phy_def,
                                                t2v_prompt=t2v_prompt)
            },
            {
                "from": "gpt",
                "value": OUT_TEMPLATE.substitute(thinking=thinking,
                                                 v_score=v_score,
                                                 t_score=t_score,
                                                 p_score=p_score),
            }
            ],
            "videos": [
                f"videos/{video_name}.mp4"
            ]
        }
        convs.append(conv)
            
    dataset = Dataset.from_list(convs)
    # dataset.push_to_hub(repo_id=REPO_ID,token=HF_TOKEN,private=False)
    
    tmp_save_path=f"{sft_data_name}.json"
    with open(tmp_save_path, "w") as f:
        json.dump(convs, f, indent=4)
    upload_file(
        path_or_fileobj=tmp_save_path,
        path_in_repo=tmp_save_path,
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(tmp_save_path)
    
    test_path=f"{sft_data_name}_test.json"
    with open(test_path, "w") as f:
        json.dump(test_data, f, indent=4)
    upload_file(
        path_or_fileobj=test_path,
        path_in_repo=test_path,
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(test_path)
    
    zip_file=f"{sft_data_name}.zip"
    print("zipping videos...")
    with zipfile.ZipFile(zip_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for v_p in tqdm(video_abs_paths):
            f_name=v_p.split('/')[-1]
            if v_p.endswith('.mp4'):
                zipf.write(v_p, arcname=f_name)     
    upload_file(
        path_or_fileobj=zip_file,
        path_in_repo=zip_file,
        repo_id=VIDEO_REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(zip_file)
    
    


if __name__ == "__main__":
    REPO_ID="hexuan21/vs2_sft"
    VIDEO_REPO_ID="hexuan21/vs2_sft_video"
    HF_TOKEN=os.environ["HF_TOKEN"]
    create_repo(
            repo_id=REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    
    
    create_repo(
            repo_id=VIDEO_REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    
    TEST_NUM=300
    sft_data_name="sft_17k"
    data_paths=[
        f"thinking_final/{fname}" for fname in os.listdir("thinking_final") if sft_data_name in fname 
    ]
    video_save_dir=f"/data/xuan/videoscore2/f_v_all/videos"

    # download_video(data_paths,video_save_dir,max_workers=8)
    
    build_sft_data(data_paths,sft_data_name,video_save_dir)
    
    
    
    # parquet_names=[
    #     "lab_12k_0712"
    # ]
    # sft_batch_name="lab_12k_0712"
    # repo_id="hexuan21/vs2_raw_comment"
    # video_save_dir=f"/data/xuan/videoscore2/f_v_all/videos"
    # download_video_2(repo_id,parquet_names,video_save_dir,max_workers=8)
