import json
import os
from string import Template
from datasets import Dataset, Features, Value
from huggingface_hub import upload_file, create_repo
import urllib.request
import warnings
import zipfile
from tqdm import tqdm

# LF data/dataset_info.json
"""
"dataset_name": {
  "file_name": "data.json",
  "formatting": "sharegpt",
  "columns": {
    "messages": "conversations",
    "videos": "videos"
  }
}
"""

"""
[
  {
    "conversations": [
      {
        "from": "human",
        "value": "<video>user instruction"
      },
      {
        "from": "gpt",
        "value": "model response"
      }
    ],
    "videos": [
      "video path (required)"
    ]
  }
]
"""

visual_def='''
The dimension 'visual quality' cares about the video's visual and optical propertities, including 'resolution, overall clarity, local blurriness, smoothness, stability of brightness/contrast, distortion/misalignment, abrupt changes, and any other factors the affect the watching experience'. The keywords written by the annotators are also mostly derived from the above factors.
'''

t2v_def='''
The dimension 't2v_alignment' mainly assesses whether the generated video fully and accurately depicts the elements mentioned in the text prompt, such as characters, actions, animals, etc., as well as background, quantity, color, weather, and so on. So the keywords written by annotators sometimes only indicate the elements that are missing from the video.
'''

phy_def='''
The dimension 'physical consistency' mainly examines whether there are any violations of common sense, physical laws, or any other aspects in the video that appear strange or unnatural. Most of the keywords provided by annotators point out the specific abnormalities or inconsistencies they observed in the video.
'''

SYS_PROMPT='''
You are an expert for evaluating and thinking about the quality of AI videos from diverse dimensions.
'''


def _download_video(url,name,save_dir):
    video_path=os.path.join(save_dir,f"{name}.mp4")
    os.makedirs(os.path.dirname(video_path),exist_ok=True)
    if not os.path.exists(video_path):
        try:
            urllib.request.urlretrieve(url, video_path) 
            return video_path
        except Exception as e:
            print(e)
            return None
    else:
        warnings.warn(f"Video {name} Already Exists!")
        return video_path

    

def build_sft_data(path,uid):
    data=json.load(open(path,"r",encoding='utf-8'))
    data=_modify_score(data)
    convs=[]
        
    for x in tqdm(data):
        video_name=x["video_name"]
        video_url=x["video_url"]
        if _download_video(video_url,video_name,video_save_dir) is None:
            continue
        
        prompt=x["prompt"]
        visual_score=x["visual_score"]
        t2v_score=x["t2v_score"]
        phy_score=x["phy_score"]
        thinking=x["thinking"]
        
        # sharegpt format
        human_input=f"""
        <video>
        {SYS_PROMPT}
        We would like to evaluate its quality from three dimensions: 'visual quality', 'text-to-video alignment' and 'physical consistency'. Below is the definition of each dimension: 
        (1) {visual_def}
        (2) {t2v_def}
        (3) {phy_def}
        Here we provide an AI video generated by text-to-video models and its text prompt: 
        {prompt}.
        Based on the video content and the dimension definitions, please evaluate the video quality, provide (1) the thinking process, and (2) the quality score. 
        The quality score must be in 1.0 - 5.0, and the thinking process should be of appropriate length and expression.
        """
        
        model_output=f"""
        ### Thinking Process:
        {thinking}
        
        ### Score:
        (1) visual quality: {visual_score}
        (2) text-to-video alignment: {t2v_score}
        (3) physical consistency: {phy_score}
        """
        
        
        conv={
            "conversations": [
            {
                "from": "human",
                "value": human_input
            },
            {
                "from": "gpt",
                "value": model_output,
            }
            ],
            "videos": [
                f"videos/{video_name}.mp4"
            ]
        }
        convs.append(conv)
            
    dataset = Dataset.from_list(data)
    dataset.push_to_hub(repo_id=REPO_ID,token=HF_TOKEN,private=False)
    
    zip_file=f"{uid}.zip"
    with zipfile.ZipFile(zip_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for fname in os.listdir(video_save_dir):
            if fname.endswith('.mp4'):
                full_path = os.path.join(video_save_dir, fname)
                zipf.write(full_path, arcname=fname)            
    upload_file(
        path_or_fileobj=zip_file,
        path_in_repo=zip_file,
        repo_id=VIDEO_REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(zip_file)
    
    tmp_save_path="vs2_data_sft.json"
    with open(tmp_save_path, "w") as f:
        json.dump(dataset.to_dict(), f, indent=2)
    upload_file(
        path_or_fileobj=tmp_save_path,
        path_in_repo=tmp_save_path,
        repo_id=REPO_ID,
        repo_type="dataset",
        token=HF_TOKEN
    )
    os.remove(tmp_save_path)


if __name__ == "__main__":
    REPO_ID="hexuan21/vs2_sft"
    VIDEO_REPO_ID="hexuan21/vs2_sft_video"
    HF_TOKEN=os.environ["HF_TOKEN"]
    create_repo(
            repo_id=REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    create_repo(
            repo_id=VIDEO_REPO_ID,
            token=HF_TOKEN,
            repo_type='dataset',
            private=False,
            exist_ok=True
        )
    
    uid="batch_91_100_com"
    video_save_dir=f"./videos_tmp_{uid}/"
    data_path=""
    build_sft_data(data_path,uid)
    
